#ifndef _DEC_TYPES_
#define _DEC_TYPES_

namespace Dec
{
	enum PrimitiveTopology
	{
		POINT_LIST,
		LINE_LIST,
		LINE_STRIP,
		TRIANGLE_LIST,
		TRIANGLE_STRIP,
		TRIANGLE_FAN,
		LINE_LIST_WITH_ADJACENCY,
		LINE_STRIP_WITH_ADJACENCY,
		TRIANGLE_LIST_WITH_ADJACENCY,
		TRIANGLE_STRIP_WITH_ADJACENCY,
		PATCH_LIST,
	};

	enum ShaderStage
	{
		VERTEX_SHADER = 0,
		TESSELLATION_CONTROL_SHADRER,
		TESSELLATION_EVALUATION_SHADER,
		GEOMETRY_SHADER,
		FRAGMENT_SHADER,
		SHADER_COUNT
	};

	enum AccessFlags
	{
		CPU_READ = 1,
		CPU_WRITE = CPU_READ << 1,
		CPU_READWRITE = CPU_READ | CPU_WRITE,
		CPU_WRITECOMBINED = CPU_WRITE << 1,
		GPU_READ = CPU_WRITECOMBINED << 1,
		GPU_WRITE = GPU_READ << 1,
		GPU_READWRITE = GPU_READ | GPU_WRITE,
		GPU_EXCUTION = GPU_WRITE << 1
	};

	enum MemoryType
	{
		TYPE_VIRTUAL = 1,
		TYPE_PHYSICAL = TYPE_VIRTUAL << 1,
		TYPE_COMMITTED = TYPE_VIRTUAL | TYPE_PHYSICAL
	};
};

#endif // _DEC_TYPES_
